# conf.py
"""
Configuration file for the Sphinx documentation builder.

This file contains a variety of settings and options to customize the
documentation generation process for the "Registro de Refeições" project.

Key Features:
- Adds the project root directory to `sys.path` for module discovery.
- Configures Sphinx extensions like autodoc, napoleon, intersphinx, and more.
- Sets up HTML output with the modern "Furo" theme.
- Includes options for autodoc, napoleon, intersphinx, and autosummary.
- Mocks imports for unavailable or large dependencies during the build process.

For more details on Sphinx configuration, visit:
https://www.sphinx-doc.org/en/master/usage/configuration.html
"""
# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
import os
import sys
# Add the project root directory to the path
sys.path.insert(0, os.path.abspath('../..'))  # Adjust this if your docs structure differs
print(sys.path)  # Debugging line to check the sys.path
# -- Project information -----------------------------------------------------

project = 'Registro de Refeições'  # pylint: disable=invalid-name
copyright = '2024-2025, Mateus G Pereira'  # pylint: disable=redefined-builtin,invalid-name
author = 'Mateus G Pereira'  # pylint: disable=invalid-name

# The full version, including alpha/beta/rc tags - you might want to fetch this dynamically
# from your package, e.g., using importlib.metadata if you set it up in pyproject.toml
# For now, using a placeholder.
release = '0.1.0'  # pylint: disable=invalid-name
version = '0.1'  # pylint: disable=invalid-name

# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    'sphinx.ext.autodoc',        # Include documentation from docstrings
    'sphinx.ext.napoleon',       # Support for Google and NumPy style docstrings
    'sphinx.ext.intersphinx',    # Link to other projects' documentation
    'sphinx.ext.viewcode',       # Add links to source code
    'sphinx.ext.todo',           # Support for todo items
    'sphinx.ext.autosummary',    # Generate summary tables
    'sphinx_copybutton',       # Add a "copy" button to code blocks
    'sphinx.ext.githubpages',    # Helps with GitHub Pages deployment
]

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
# source_suffix = ['.rst', '.md']
source_suffix = '.rst'  # pylint: disable=invalid-name

# The root document. (Replaces master_doc in Sphinx 4.0+)
root_doc = 'index'  # pylint: disable=invalid-name

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = 'pt_BR'  # pylint: disable=invalid-name

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']

# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages. See the documentation for
# a list of builtin themes.
# Popular options: 'alabaster', 'sphinx_rtd_theme', 'furo'
html_theme = 'furo'  # pylint: disable=invalid-name # Using the modern Furo theme

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']

# You can add a logo here if you have one
# html_logo = "_static/logo.png"

# Theme options are theme-specific and customize the look and feel of a theme
# further. For a list of options available for each theme, see the
# documentation.
# html_theme_options = {}

# -- Options for autodoc ----------------------------------------------------

# Automatically extract typehints when specified and place them in
# descriptions of the relevant function/method.
autodoc_typehints = "description"  # pylint: disable=invalid-name

# Don't show class signature with the class name.
autodoc_class_signature = "separated"  # pylint: disable=invalid-name

# Default options for autodoc directives. Applied to all autodoc directives.
autodoc_default_options = {
    'members': True,             # Document members (methods, attributes)
    'member-order': 'bysource',  # Order members as they appear in source
    'undoc-members': True,       # Document members without docstrings (use with caution)
    'show-inheritance': True,    # Show base classes
    # 'private-members': True,   # Uncomment to document private members (_*)
    # 'special-members': '__init__', # Uncomment to document special members like __init__
}

# Mock imports for modules that might not be available during build
# Especially GUI libraries, hardware-specific libraries, or large dependencies.
autodoc_mock_imports = [
    'tkinter',
    'ttkbootstrap',
    'gspread',
    'google',          # Keep top-level
    'google.auth',
    'google.oauth2',
    'google.auth.transport',  # Keep necessary submodules
    'google.auth.transport.requests',
    'google.auth.exceptions',
    'google.oauth2.credentials',
    'google_auth_oauthlib',
    'google_auth_oauthlib.flow',
    'xlsxwriter',
    'xlsxwriter.exceptions',
    'fuzzywuzzy',
    'ctypes',
    'sqlalchemy',     # Keep top-level
    'sqlalchemy.orm',  # Keep necessary submodules
    'sqlalchemy.exc',
    'sqlalchemy.dialects',
    'sqlalchemy.dialects.sqlite',
    # Explicitly add the base class if needed, although mocking sqlalchemy.exc should cover it
    # 'sqlalchemy.exc.SQLAlchemyError',
    # 'sqlalchemy.exc.IntegrityError',
]


# -- Options for Napoleon ---------------------------------------------------

# Napoleon settings to parse Google style docstrings
napoleon_google_docstring = True  # pylint: disable=invalid-name
napoleon_numpy_docstring = False  # pylint: disable=invalid-name # Explicitly disable NumPy style
napoleon_include_init_with_doc = True  # pylint: disable=invalid-name
napoleon_include_private_with_doc = False  # pylint: disable=invalid-name
napoleon_include_special_with_doc = True  # pylint: disable=invalid-name
napoleon_use_admonition_for_examples = False  # pylint: disable=invalid-name
napoleon_use_admonition_for_notes = False  # pylint: disable=invalid-name
napoleon_use_admonition_for_references = False  # pylint: disable=invalid-name
napoleon_use_ivar = False  # pylint: disable=invalid-name
napoleon_use_param = True  # pylint: disable=invalid-name
napoleon_use_rtype = True  # pylint: disable=invalid-name
napoleon_preprocess_types = True  # pylint: disable=invalid-name
napoleon_type_aliases = None  # pylint: disable=invalid-name
napoleon_attr_annotations = True  # pylint: disable=invalid-name

# -- Options for intersphinx ------------------------------------------------

# Example configuration for intersphinx: refer to the Python standard library.
intersphinx_mapping = {
    'python': ('https://docs.python.org/3', None),
    'sqlalchemy': ('https://docs.sqlalchemy.org/en/20/', None),  # Check version
    'ttkbootstrap': ('https://ttkbootstrap.readthedocs.io/en/latest/', None),
    # Add mappings for other libraries like gspread if available and needed
    # 'gspread': ('https://gspread.readthedocs.io/en/latest/', None),
}

# -- Options for todo -------------------------------------------------------

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = True  # pylint: disable=invalid-name

# -- Options for Autosummary ------------------------------------------------
# Turn on sphinx.ext.autosummary
autosummary_generate = True  # pylint: disable=invalid-name
# Don't document imported members within modules
autosummary_imported_members = False  # pylint: disable=invalid-name

# --- Optional: Copybutton configuration ---
# Exclude prompts (>>> , ... ) and output C# console prompts
copybutton_prompt_text = (  # pylint: disable=invalid-name
    r">>> |\.\.\. |\$ |In \[\d*\]: | {2,5}\.\.\.: | {5,8}: ")  # Turn on sphinx.ext.autosummary
# Turn on sphinx.ext.autosummary
copybutton_prompt_is_regexp = True  # pylint: disable=invalid-name
